// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SAP_AdresToLatLong.Data;

#nullable disable

namespace SAP_AdresToLatLong.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SAP_AdresToLatLong.Models.PostGeocodeData", b =>
                {
                    b.Property<int>("DocNum")
                        .HasColumnType("integer");

                    b.Property<int>("CardCode")
                        .HasColumnType("integer");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(10, 6)");

                    b.HasKey("DocNum");

                    b.ToTable("PostGeocodeData");
                });

            modelBuilder.Entity("SAP_AdresToLatLong.Models.SAPData", b =>
                {
                    b.Property<int>("DocNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DocNum"));

                    b.Property<string>("BillToAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CardCode")
                        .HasColumnType("integer");

                    b.Property<string>("SendToAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DocNum");

                    b.ToTable("SAPData");
                });

            modelBuilder.Entity("SAP_AdresToLatLong.Models.PostGeocodeData", b =>
                {
                    b.HasOne("SAP_AdresToLatLong.Models.SAPData", "SAPData")
                        .WithOne("PostGeocodeData")
                        .HasForeignKey("SAP_AdresToLatLong.Models.PostGeocodeData", "DocNum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SAPData");
                });

            modelBuilder.Entity("SAP_AdresToLatLong.Models.SAPData", b =>
                {
                    b.Navigation("PostGeocodeData")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
